# Generated by Django 6.0.6 on 2026-07-01 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=1)),
                ('escudo', models.ImageField(upload_to='escudos/')),
                ('bandera', models.ImageField(upload_to='banderas/')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Posicion', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('alias', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('seleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_panini.seleccion')),
            ],
        ),
    ]
