# Generated by Django 6.0.6 on 2026-07-12 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_panini', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='anime_favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.CharField(max_length=100)),
                ('personaje', models.CharField(max_length=1)),
                ('Portada_Anime', models.ImageField(upload_to='Portadas/')),
                ('Logo_anime', models.ImageField(upload_to='animes_L/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('lvl_power', models.CharField(max_length=50)),
                ('tier', models.IntegerField()),
                ('apodo', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='jugadores/')),
                ('seleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_panini.anime_favorito')),
            ],
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
        migrations.DeleteModel(
            name='Seleccion',
        ),
    ]
